### PR TITLE
Adds a pydantic V2 compatibility layer

### LINKED ISSUE #215: Support for pydantic v2
https://github.com/cloudevents/sdk-python/blob/main/cloudevents/pydantic/event.py#L87

https://docs.pydantic.dev/latest/migration/

### PR DESCRIPTION
**Pull request by febus982**
Fixes #215

## Changes
Adds a compatibility layer allowing to install the SDK together with pydantic v2, while still using the v1 implementation. Further improvements would be a native pydantic v2 implementation.

## One line description for the changelog
Allows to install the SDK together with pydantic v2.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by duglin** [comment]
ping @Klaudioz @denismakogon @xSAVIKx @cumason123

**Comment by febus982** [comment]
There’s a typing issue, I think it’s safe to ignore it, is it fine to ignore it? (don't want to trigger too many minutes on workers)
 
I have started working on the native Pydantic V2 implementation. 
- would it be enough to match the existing tests for v1?
- there are notes about serialization/deserialization performance issues in the current implementation. Pydantic V2 should bring great performance improvements. Is there any performance testing configured that we can run?

**Review by xSAVIKx — COMMENTED** [review]
@febus982 please let me know if you'd add ignores for MyPy or whether I should jump in and add them.

**Comment by febus982** [comment]
Hey @xSAVIKx 

> Regarding the typings issue, I believe we'll need to suppress that one, but not just ignore it. Can you please suppress it with # type: ignore?

Yes, I meant ignore for us humans, and suppress it. I'll add ` # type: ignore`

> As for the tests, with the change you made, I believe our CI is now only running tests against v2 and is not running tests against v1 anymore. Having tests with both v1 and v2 versions of Pydantic is gonna require quite some more changes to the way the repo is managed.

If this is very important I can try to see if I can configure different tox environments, however as pydantic V1 development is stopped (except for critical bug fixes and security issues) the double time required for tests is something to be considered. Let me know if you want me to address this as well.

**Comment by xSAVIKx** [comment]
Neah, I just checked the internals of the v1 compatibility layer and it feels like they just copied over the whole v1 library 😅 just fixing typings to please mypy and make the check pass is good enough

**Comment by febus982** [comment]
@xSAVIKx I think it's ready to go (hopefully tests will pass, tox is happy on my local machine)

**Review by xSAVIKx — APPROVED** [review]

**Pull request merged**
