### PR TITLE
ignore datacontenttype when using to_binary()

### PR DESCRIPTION
**Pull request by xinydev**
Fixes https://github.com/cloudevents/sdk-python/issues/137

## One line description for the changelog

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by xinydev** [comment]
I change the  `contenttype` to `datacontenttype` other than add `datacontenttype` like `["data", "extensions", "contenttype","datacontenttype"]`  

because all props are set by  `self.Properties()`[code](https://github.com/cloudevents/sdk-python/blob/master/cloudevents/sdk/event/base.py#L167) ,  and there is no such headers like `ce-contenttype` in [spec](https://github.com/cloudevents/spec/blob/v1.0.1/http-protocol-binding.md)

**Comment by xinydev** [comment]
@di  Could you take a look at this PR?

**Comment by di** [comment]
@xinydev Makes sense to me, can you get the tests passing and also [sign your commits](https://github.com/cloudevents/sdk-python/pull/138/checks?check_run_id=2671207158) so DCO passes?

**Comment by xinydev** [comment]
> @xinydev Makes sense to me, can you get the tests passing and also [sign your commits](https://github.com/cloudevents/sdk-python/pull/138/checks?check_run_id=2671207158) so DCO passes?

I get the tests passing in my forked repo. Could you please approve running tests workflows?

**Review by di — APPROVED** [review]

**Pull request merged**
