### PR TITLE
Fix typo in extensions

### PR DESCRIPTION
**Pull request by bonnevm**
- Link to issue this resolves

- What I did
Fixed a typo in the "extensions" setter

- How I did it
Added the missing "s"

- How to verify it

- One line description for the changelog
Fixed typo in the "extensions" setter

### CODE REVIEW

**Comment by bonnevm** [comment]
@Lawouach @evankanderson @denismakogon PTAL

**Comment by Lawouach** [comment]
Thanks for the heads up! i'll look how this impacts me, but I think it's safe on my end.

**Comment by denismakogon** [comment]
sorry, was out for a while.

**Comment by denismakogon** [comment]
version 0.2.4 released.

**Pull request merged**
