### PR TITLE
Fix a broken link to a sample in the README

### PR DESCRIPTION
**Pull request by guyzyl**
## Changes
Fix a broken link to a sample in the README.

## One line description for the changelog
Fix a broken link to a sample in the README.

- [X] Tests pass
- [X] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by grant — APPROVED** [review]

**Comment by grant** [comment]
Thanks @guyzyl . Can you fix the DCO issue?

I believe this will fix it:

`git commit --amend --no-edit --signoff`

**Comment by guyzyl** [comment]
@grant done.

**Comment by xSAVIKx** [comment]
Hello @guyzyl. Thx for your contribution. Can you please rebase your changes?

**Comment by guyzyl** [comment]
@xSAVIKx done

**Comment by xSAVIKx** [comment]
Hey @guyzyl, I'm sorry to bother, but this seems to have no effect. I don't think there's a reason to merge this.

**Pull request closed without merging**
