### PR TITLE
Modified content-type to abide by attribute naming conventions for cloudevents

### LINKED ISSUE #211: `cloudevents.kafka.to_binary` checks for a `content-type` attribute, which would not be a valid attribute name
https://github.com/cloudevents/sdk-python/blob/ef982743b68866abbe0049dbffac76f5a2e3efb4/cloudevents/kafka/conversion.py#L90

This will call `CloudEvent._get_attributes()["content-type"]` but a `content-type` attribute will violate the attribute naming rules:

https://github.com/cloudevents/spec/blob/30f1a081743bfe06b45b85519dd145f14a1ad22c/cloudevents/spec.md?plain=1#L173-L175

> CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.

It is not really that clear to me why this is being done, but it also causes some problems when `event` is a Pydantic cloud event, but regardless of that it seems pretty clear that it is wrong.

### PR DESCRIPTION
**Pull request by vivjd**
Fixes #211 

## Changes
The `content-type` attribute will violate the attribute naming rules, so the attribute has been modified to `datacontenttype`.

## One line description for the changelog
Converted `content-type` to `datacontenttype` for `cloudevents`.

- [x] Tests pass

### CODE REVIEW

**Comment by xSAVIKx** [comment]
Hey @vivjd, thx for opening the PR.

Unfortunately your change is not really what the desired behavior should be. I've mentioned the desired one here: https://github.com/cloudevents/sdk-python/issues/211#issuecomment-1533212334

So if you're up for changing this to comply with the desired behavior I'd be glad to review the PR.

**Comment by vivjd** [comment]
Hi @xSAVIKx! Thank you for you feedback. I've reread the original issue and the desired behavior, and changed it accordingly in my PR. If you could review the PR that would be great! Thank you for your time!

**Review by xSAVIKx — COMMENTED** [review]
@vivjd overall LGTM. Would you be so kind to add a test case for this change in kafka-related test suite?

**Comment by vivjd** [comment]
Hi @xSAVIKx, I changed the test cases to match the change. Could you please kindly review this again? Thank you in advance!

**Review by xSAVIKx — APPROVED** [review]

**Comment by Cali0707** [comment]
Hey @xSAVIKx @duglin would one of you be able to approve the workflows on this PR?

**Comment by xSAVIKx** [comment]
Sorry, my bad. I was.pretty sure I did that when I was reviewing the PR

**Pull request merged**
