### PR TITLE
Add correct type annotations for tuple return types

### PR DESCRIPTION
**Pull request by grant**
Reducing style errors. See:

Fixes https://github.com/cloudevents/sdk-python/issues/125

### CODE REVIEW

**Comment by grant** [comment]
R: @anniefu?

**Review by anniefu — APPROVED** [review]

**Comment by grant** [comment]
Needs a SDK maintainer.
R: @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
I am not actually a maintainer here, but I can ping in the Slack for review. :)

**Comment by GrahamCampbell** [comment]
Just noticed this is only 1 hour old. I'll give it a few days before pinging in here.

**Comment by grant** [comment]
@cloudevents/maintainers Any takers for approving?

**Comment by grant** [comment]
Can we get an approver to merge?

**Comment by duglin** [comment]
@denismakogon @cumason123 either of you have time to look at look at this one?

**Comment by grant** [comment]
@duglin any luck getting an approver for this minor PR?

**Comment by duglin** [comment]
@GrahamCampbell any comments?

**Comment by grant** [comment]
> @grant since you're a maintainer and it's been so long, I think you should just merge it

Merging can only be performed with 1 approving review from someone who has maintainer acls. Need an approver review still :)

**Review by duglin — APPROVED** [review]

**Comment by duglin** [comment]
go for it now

**Comment by grant** [comment]
Thanks.

**Pull request merged**
